FROM jenkins/jenkins:$jenkinsversion-alpine
USER root

RUN apk add --no-cache bash curl git openssh-client

RUN curl -L -o /tmp/docker-$dockerversion.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$dockerversion.tgz \
    && tar -xz -C /tmp -f /tmp/docker-$dockerversion.tgz \
    && mv /tmp/docker/docker /usr/bin \
    && rm -rf /tmp/docker-$dockerversion /tmp/docker

RUN curl -L -o /tmp/docker-compose https://github.com/docker/compose/releases/download/$dockercomposeversion/docker-compose-Linux-x86_64 \
    && mv /tmp/docker-compose /usr/bin \
    && chmod 500 /usr/bin/docker-compose \
    && rm -rf /tmp/docker-compose

USER jenkins

